### ISSUE TITLE
Redundant assignment of baseUrl

### ISSUE THREAD

**Issue by DemonDaddy22** [udacity/nd035-c1-spring-boot-basics-examples#6]
There's a redundant assignment of baseUrl which can be confusing.
[This](https://github.com/udacity/nd035-c1-spring-boot-basics-examples/blob/4f8b39f00635b4669876676e7dfbd1924ef0b863/udacity-jwdnd-c1-l5-final-review-solution-master/src/test/java/com/udacity/jwdnd/c1/review/ReviewApplicationTests.java#L41) is the file containing the above-mentioned redundancy.

**Comment by UAnjali** [comment]
Thanks for bringing this to our notice. We have changed the file based on your suggestion. 
Thank you
