### ISSUE TITLE
Skim.wtf issue

### ISSUE THREAD

**Issue by etamys** [udacity/nd035-c1-spring-boot-basics-examples#9]
hello sir
I'm really thankful to you , you did very good work by uploading whole java course on  skim.wtf site

it's very helpful for me. but now your site domain is expired.
can please renew it. i need this.
if it's not possible can you please provide me any other know link.. please please i need it for my learning.

**Comment by cesarnet** [comment]
Buenos días,

yo me he limitado a enlazar en github los ficheros de un curso de udacity,
no los he subido a ningún sitio.

Los originales están en:
https://github.com/udacity/nd035-c1-spring-boot-basics-examples

Saludos
